spring:
  application:
    name: codedash
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/codedash}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  

